export { default as Profile } from './Profile' 
export { default as SearchBar } from './SearchBar'
export { default as Register } from './Register'
export { default as JobCard } from './JobCard'
export { default as Results } from './Results'