# Generated by Django 3.2.3 on 2021-05-16 17:09

import careers.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=careers.storage_backends.PrivateMediaStorage(), upload_to='profiles/cv'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=careers.storage_backends.PrivateMediaStorage(), upload_to='profiles/image'),
        ),
    ]
