# Generated by Django 3.2.3 on 2021-05-14 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('saved', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('interviewed', models.BooleanField(default=False)),
                ('offered', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
