# Generated by Django 3.2.3 on 2021-05-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
