# Generated by Django 3.2.3 on 2021-05-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userreward_reward'),
        ('users', '0002_auto_20210516_1809'),
    ]

    operations = [
    ]
