# Generated by Django 3.2.3 on 2021-05-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210517_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='group',
            new_name='reward',
        ),
    ]
