# Generated by Django 3.2.3 on 2021-05-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210514_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
