version: "3.9"
   
services:
  db:
    image: postgres
    ports: 
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  dbdata: