# Generated by Django 3.2.3 on 2021-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('point_change', models.IntegerField(default=0)),
                ('one_time', models.BooleanField(default=False)),
            ],
        ),
    ]
