# Generated by Django 3.2.3 on 2021-05-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='one_time',
            field=models.BooleanField(default=False),
        ),
    ]
